engines:
  eslint:
    channel: "eslint-3"
    enabled: true
    parserOptions:
      sourceType: 'module'
    config: .eslintrc.yml
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
   paths:
   - "app/**/*"