engines:
  eslint:
    enabled: true
    channel: "eslint-2"
    parserOptions:
      sourceType: 'module'
    config:
      extensions:
      - .es6
      - .js
      - .jsx
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
   paths:
   - "app/**/*"