engines:
  eslint:
    enabled: true
    channel: "eslint-3"
    config:
      config: ".eslintrc.yml"
      extensions:
      - ".js"
      - ".jsx"
    checks:
      complexity:
        enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
   paths:
   - "app/**/*"