parserOptions:
  sourceType: "module"
  ecmaVersion: 8
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
env:
  browser: true
  es6: true
  node: true
extends:
  - "eslint:recommended"