parserOptions:
  sourceType: "module"
  parser: "babel-eslint"
  ecmaVersion: 8
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
env:
  browser: true
  es6: true
  node: true
plugins:
  - "react"
extends:
  - "eslint:recommended"
  - "eventbrite-react"
rules:
  "react/prop-types": [2]
  "react/jsx-indent-props": [2, 2]
  "react/jsx-indent": [2, 2]
  "indent": [2, 2]