parserOptions:
  sourceType: "module"
  parser: "babel-eslint"
  ecmaVersion: 6
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
env:
  browser: true
  es6: true
  node: true
extends:
  - "eslint:all"